#+TITLE: NTNU PhD thesis template.
#+OPTIONS: ^:nil
This is a latex templates for NTNU PhD thesis. This template supports thumb indexes for papers - and also auxiliar papers.
* About
PhD thesis latex template for NTNU PhD thesis.
Does not include titlepage (the printers will make this for you, at least NTNU fagtrykk) - but it can be generated by "\ntnutitle'" ([[file:phdntnu.cls::newcommand{ntnutitle}{][Link to phdntnu.cls definition]])
* Requirements
PDFLatex/XeTeX.
* Usage
- Read through main.tex and adjust accordingly
- Use "bibliography.bib" for bibliography or adjust in phdstyle.sty to point to another file.
- Add papers and auxially papers in "papers/paper1/" and "papers/paper2/" ..
  etc - the examples show how to swap the premables/headers for "standalone"
  documentclass. if any of the papers need special latex packages or macros, add
  to main.tex
- The examples also shows how to reference figures.


Then compile
#+begin_src bash
make
#+end_src
or
#+begin_src bash
latexmk -pdf -pdflatex=xelatex --synctex=1 -interaction=nonstopmode  -file-line-error  main.tex
#+end_src
* Contact
Please use fork/PR/issues - contact me at bjornmm@ntnu.no if you have any questions
